---

- name: Base RHEL Configuration
  hosts:
    - openstack
    - scaleio
  max_fail_percentage: 0
  roles:
    - subscription-manager
    - common

- name: OpenStack Common
  hosts: openstack
  max_fail_percentage: 0
  roles:
    - openstack-common

- include: controllers.yml
- include: swift.yml
- include: compute-nodes.yml
- include: scaleio-nodes.yml
- include: demo.yml

- name: OpenStack Firewall
  hosts: openstack
  max_fail_percentage: 0
  roles:
    - firewall
