---
- name: Base RHEL Configuration
  hosts:
    - openstack
    - scaleio
  max_fail_percentage: 0
  roles:
    - subscription-manager
    - common

- name: OpenStack Common
  hosts: openstack
  max_fail_percentage: 0
  roles:
    - openstack-common

- include: controllers.yml
- include: swift.yml
- include: compute-nodes.yml
- include: scaleio-nodes.yml

- name: run demo play
  include: demo.yml
  when: "{{run_demo}}"
  tags: demo
